name: Dockerize spring-booot application
on: push
jobs:
  build-container:
    name: Build docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to Github Package
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/sonarqube-demo
          tags: latest, ${{ github.run_number }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: slaimimed/sonarqube-demo
          tags: latest, ${{ github.run_number }}
