name: Dockerize spring-booot application
on: push
jobs:
  build-container:
    name: Build docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: slaimimed/sonarqube-demo
          tags: latest, ${{ github.run_number }}
